### ISSUE TITLE
maxValuesPerFacet is missing in MeiliSearchSettings

### ISSUE THREAD

**Issue by wetgi** [sanders41/meilisearch-python-async#271]
Hey it would be nice to have the `maxValuesPerFacet` in the `MeiliSearchSettings` model.

**Comment by sanders41** [comment]
Thanks for the report @wetgi! Do you have any interest and creating a PR to add it? If not it's ok, I will do it.

**Comment by wetgi** [comment]
I made a PR: https://github.com/sanders41/meilisearch-python-async/pull/273
