### ISSUE TITLE
Update CONTRIBUTING.md with instructions for just

### ISSUE THREAD

**Issue by sanders41** [sanders41/meilisearch-python-async#443]
Remove references it Make and replace with instruction for just.

**Comment by Himanshuch1708** [comment]
Can you describe it more?

**Comment by sanders41** [comment]
I don't have a good way to put the updated text into the issue because formatting gets messed up, but the change is similar to the references to `ruff` [here](https://raw.githubusercontent.com/sanders41/meilisearch-tui/main/CONTRIBUTING.md). The sections that mention `make` should be updated to `just`.

Some of the commands will be different, to see a full list of commands available here and where they are different run `just --list`, or you can look at the [justfile](https://github.com/sanders41/meilisearch-python-async/blob/main/justfile)
