### ISSUE TITLE
Ideas for benchmarking sync vs. async

### ISSUE THREAD

**Issue by prrao87** [sanders41/meilisearch-python-async#627]
Based on the [code](https://github.com/sanders41/meilisearch-python-async/blob/d6a9448bc4f0473a59cd89ce50fcde15fbca6942/benchmark/run_benchmark.py#L86) you have to benchmark sync vs. async performance, I noticed a couple of problems.
 
- It doesn't make sense to search the same term ("the") again and again, as nearly every DB implements caching for queries that are repeated
- On the flip side, purely random pre-generated data isn't ideal because we'd want to ensure that the same random elements are generated for either solution.
 
My solution to the movie dataset benchmark would be as follows:

- Fix a random seed in the benchmark script
- Sample a set of movies names from the list of all movie names, but set the seed in the sampling so it's perfectly reproducible

So, something like this:

```python
import random

random.seed(10)

# Retrieve full list of movies from the DB for sampling

movie_list = ['The Dark Knight', 'The Wizard of Oz', 'Citizen Kane', 'The Shawshank Redemption', 'Pulp Fiction']

movie = random.sample(movie_list, 1000)
```
Because the random seed guarantees the same combination of movies each time, there's no need to store the movies that you benchmark on in a file -- you could potentially just sample from a static dump of movie names on disk just prior to running the benchmark, and you'd have the same reproducible list of movies in both the sync and async benchmarks to compare against.

I feel like random sampling with reproducibility via a seed will ensure a fairer benchmark comparison.

Happy to issue a PR testing this approach if you are caught up with other priorities -- I just wanted to check with you before putting in the work.

**Comment by sanders41** [comment]
Thanks @prrao87, I would happily take a PR for this.

**Comment by prrao87** [comment]
Will get on that and report back in a day or two!
