### ISSUE TITLE
Why there default cache for search?

### ISSUE THREAD

**Issue by long2ice** [sanders41/meilisearch-python-async#628]
I see in this commit: https://github.com/sanders41/meilisearch-python-async/commit/1715656e943ca41eae56d233bbac25443fb72997

Which cause my application OOM and cost my a lot of time to debug it...

I know cache is used to improve search performance, but users should choice to use it or not. We need provide options for it.

**Comment by sanders41** [comment]
@long2ice I just released v1.6.2 that removes the cache until I can come up with a better solution to your issue.
